### PR TITLE
creating folder structures

### LINKED ISSUE #12: Folder structure
Use cookiecutter to populate the folder structure

### PR DESCRIPTION
**Pull request by jlee2843**
Creating folder structure following `cookiecutter `guideline. Previous README and LICENSE files have been deleted as they are overridden by the ones auto-created by `cookiecutter`.  Please review!

### CODE REVIEW

**Review by salva-u — COMMENTED** [review]
does this branch stem from an associated issue?

**Comment by jlee2843** [comment]
Oops yeah it does, I believe it's related to [Week 1 MOM](https://github.com/UBC-MDS/Pythoshop/issues/2).

**Comment by salva-u** [comment]
I added the linked issue

**Review by salva-u — APPROVED** [review]

**Review by Rachel0619 — APPROVED** [review]
Great set up.

**Pull request merged**
